# nginx proxy address - https://172.17.0.1:59056

name: nextcloud
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  app:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud-app
    domainname: ${BASE_DOMAIN_NAME:-example.com}
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      CONTAINER_NAME: nextcloud-app
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
      PUID: ${SERVICE_USER:-1000}
      PGID: ${SERVICE_GROUP:-1000}
    ports:
      - '172.17.0.1:59056:443'
    volumes:
      - './volumes/data/nextcloud:/data'
      - './volumes/config/nextcloud:/config'
    networks:
      - nextcloud
      - proxy
      - cloudflare
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://nextcloud-app:443'
      - 'cloudflare.hostname=nextcloud.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.nextcloud-app.entrypoints=http'
      - 'traefik.http.routers.nextcloud-app-secure.tls=true'
      - 'traefik.http.routers.nextcloud-app.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.nextcloud-app-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.nextcloud-app.middlewares=nextcloud-app-https-redirect'
      - 'traefik.http.routers.nextcloud-app-secure.entrypoints=https'
      - 'traefik.http.routers.nextcloud-app-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.nextcloud-app-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.nextcloud-app-secure.service=nextcloud-app'
      - 'traefik.http.services.nextcloud-app.loadbalancer.server.port=443'

networks:
  nextcloud:
    name: nextcloud
    external: false
  proxy:
    external: true
  cloudflare:
    external: true
